---
title: "EY106 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(DescTools)

df <- read_excel("~/Documents/Experiments/4.14.26 EY106 GFP.xlsx", 
    sheet = "Sheet1")

```

```{r}
#separate luminescence and fluorescence 
newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 

newdf1<- newdf %>%
  slice(seq(from = 1, to = n(), by = 2))
newdf2 <- newdf %>%
  slice(seq(from = 2, to = n(), by = 2))

min <-c(0,18.5,37,55.5,74,92.5,111,129.5,148,166.5,185,203.5,222,240.5,259,277.5,296,314.5,333,351.5,370,388.5,407,425.5,444,462.5,481,499.5,518,536.5,555,573.5,592,610.5,629,647.5,666,684.5,703,721.5,740,758.5,777,795.5,814,832.5,851,869.5,888,906.5,925,943.5,962,980.5,999,1017.5,1036) 

i <- cbind(newdf1,min)
j <- cbind(newdf2,min)
```
```{r}
colors <- c("Alive" = "steelblue", "Control" = "black", "Dead" = "red")
p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  #geom_line(aes(y = C1, color="Dead")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  geom_line(aes(y = E1, color="Alive")) + 
  geom_line(aes(y = E3, color="Control")) +
  geom_line(aes(y = G1, color="Alive")) + 
  geom_line(aes(y = G3, color="Control")) +
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Alive")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Control")) + 
  geom_line(aes(y = C5, color="Alive")) + 
  geom_line(aes(y = C7, color="Alive")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) + 
  geom_line(aes(y = E5, color="Alive")) + 
  geom_line(aes(y = E7, color="Alive")) +
  geom_line(aes(y = E9, color="Alive")) + 
  geom_line(aes(y = E11, color="Control")) +
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Alive")) +
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) +
   labs(title="EY106 Alive Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 ALum.png")
  
```
```{r}
colors <- c("Alive" = "green", "Control" = "black", "Dead" = "red")
p <- ggplot(j, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  geom_line(aes(y = C1, color="Dead")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  geom_line(aes(y = E1, color="Alive")) + 
  geom_line(aes(y = E3, color="Control")) +
  geom_line(aes(y = G1, color="Alive")) + 
  geom_line(aes(y = G3, color="Control")) +
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Alive")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Control")) + 
  geom_line(aes(y = C5, color="Alive")) + 
  geom_line(aes(y = C7, color="Alive")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) + 
  geom_line(aes(y = E5, color="Alive")) + 
  geom_line(aes(y = E7, color="Alive")) +
  geom_line(aes(y = E9, color="Alive")) + 
  geom_line(aes(y = E11, color="Control")) +
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Alive")) +
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) +
   labs(title="EY106 Fluor",
        x ="Time (min)", y = "Fluourescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 Fluor.png")
  
```

```{r Lum}
colors <- c("Female" = "purple", "Control Female" = "black", "Dead" = "red","Dead Control Female" = "gray")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Female")) + 
  geom_line(aes(y = A3, color="Female")) + 
  geom_line(aes(y = C1, color="Dead")) + 
  geom_line(aes(y = C3, color="Female")) + 
  geom_line(aes(y = E1, color="Female")) + 
  geom_line(aes(y = E3, color="Control Female")) +
  geom_line(aes(y = G1, color="Female")) + 
  geom_line(aes(y = G3, color="Control Female")) +
  labs(title="EY106 Female Lum 10 DO",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 FLum 10 DO.png")

```

```{r Lum}
colors <- c("Female" = "purple", "Control Female" = "black", "Dead" = "red","Dead Control Female" = "gray")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A5, color="Female")) + 
  geom_line(aes(y = A7, color="Female")) + 
  geom_line(aes(y = A9, color="Female")) + 
  geom_line(aes(y = A11, color="Control Female")) + 
  geom_line(aes(y = C5, color="Female")) + 
  geom_line(aes(y = C7, color="Female")) + 
  geom_line(aes(y = C9, color="Female")) + 
  geom_line(aes(y = C11, color="Control Female")) + 
  geom_line(aes(y = E5, color="Female")) + 
  geom_line(aes(y = E7, color="Female")) +
  geom_line(aes(y = E9, color="Female")) + 
  geom_line(aes(y = E11, color="Control Female")) +
  geom_line(aes(y = G5, color="Female")) + 
  geom_line(aes(y = G7, color="Female")) +
  geom_line(aes(y = G9, color="Female")) + 
  geom_line(aes(y = G11, color="Control Female")) +
  labs(title="EY106 Female Lum 12DO",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 FLum 12 DO.png")

```

```{r Fluor}

p <- ggplot(j, aes(x=min)) + 
  geom_line(aes(y = A1, color="Female")) + 
  geom_line(aes(y = A3, color="Female")) + 
  geom_line(aes(y = C1, color="Dead")) + 
  geom_line(aes(y = C3, color="Female")) + 
  geom_line(aes(y = E1, color="Female")) + 
  geom_line(aes(y = E3, color="Control Female")) +
  geom_line(aes(y = G1, color="Female")) + 
  geom_line(aes(y = G3, color="Control Female")) +
  labs(title="EY106 Female Fluor 10DO",
        x ="Time (min)", y = "Fluorescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 FFluor 10DO.png")
```

```{r Fluor}

p <- ggplot(j, aes(x=min)) + 
  geom_line(aes(y = A5, color="Female")) + 
  geom_line(aes(y = A7, color="Female")) + 
  geom_line(aes(y = A9, color="Female")) + 
  geom_line(aes(y = A11, color="Control Female")) + 
  geom_line(aes(y = C5, color="Female")) + 
  geom_line(aes(y = C7, color="Female")) + 
  geom_line(aes(y = C9, color="Female")) + 
  geom_line(aes(y = C11, color="Control Female")) + 
  geom_line(aes(y = E5, color="Female")) + 
  geom_line(aes(y = E7, color="Female")) +
  geom_line(aes(y = E9, color="Female")) + 
  geom_line(aes(y = E11, color="Control Female")) +
  geom_line(aes(y = G5, color="Female")) + 
  geom_line(aes(y = G7, color="Female")) +
  geom_line(aes(y = G9, color="Female")) + 
  geom_line(aes(y = G11, color="Control Female")) +
  labs(title="EY106 Female Fluor 12DO",
        x ="Time (min)", y = "Fluorescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY106 FFluor 12DO.png")
```

```{r}

my_vec <- numeric()

for (col in i) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)

df <- data.frame(dose=c("Female","Female","Female","Female","Female","CF","Female","Female","Female","Female","Female","CF","Female","CF","Female","Female","Female","CF","Female","CF","Female","Female","Female","CF"),
    len=c(237456.75,120333.25,118224.25,66646.25,71271.25,14846.25,428191.75,124162.75,82325.00,93425.00,43216.00,14485.50,220686.50,14790.75,107253.75,103692.50,93110.50,15207.00,74388.50,14800.00,62724.25,82029.00,98540.25,16474.25))

my_comparisons <- list( c("Female", "CF"))

p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY106 Lum AUC",
        x ="Condition", y = "Area Under Curve")
p


#ggsave("EY106 LAUC.png")
```

```{r}
my_vec <- numeric()

for (col in j) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)

df <- data.frame(dose=c("Female","Female","Female","Female","Female","CF","Female","Female","Female","Female","Female","CF","Female","CF","Female","Female","Female","CF","Female","CF","Female","Female","Female","CF"),
    len=c(684435.2,726874.2,916120.0,536583.2,707042.2,717143.2,685869.0,866049.8,940660.2,779941.5,942686.0,794565.8,674815.2,658896.0,854080.2,852924.0,785232.5,957393.5,893883.0,807460.2,838679.0,600241.8,960529.2,624106.8))

my_comparisons <- list( c("Female", "CF"))

p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY106 Fluor AUC",
        x ="Condition", y = "Area Under Curve")
p

#ggsave("EY106 FAUC.png")
```