---
title: "EY107 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(DescTools)

df <- read_excel("~/Documents/Experiments/4.24.26 EY107 GFP.xlsx", 
    sheet = "Sheet1")


```

```{r}
#separate luminescence and fluorescence 
newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 

newdf1<- newdf %>%
  slice(seq(from = 1, to = n(), by = 2))
newdf2 <- newdf %>%
  slice(seq(from = 2, to = n(), by = 2))

min <-c(0,18.5,37,55.5,74,92.5,111,129.5,148,166.5,185,203.5,222,240.5,259,277.5,296,314.5,333,351.5,370,388.5,407,425.5,444,462.5,481,499.5,518,536.5,555,573.5,592,610.5,629,647.5,666,684.5,703,721.5,740,758.5,777,795.5,814,832.5,851,869.5,888,906.5,925,943.5,962,980.5,999,1017.5,1036) 

i <- cbind(newdf1,min)
j <- cbind(newdf2,min)
```

```{r Lum}
colors <- c("Alive" = "steelblue", "Control" = "black", "Dead" = "red")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Control")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Contro")) + 
  geom_line(aes(y = C1, color="Alive")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  #geom_line(aes(y = C5, color="Dead")) + 
  geom_line(aes(y = C7, color="Control")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) + 
  geom_line(aes(y = E3, color="Alive")) +
  geom_line(aes(y = E5, color="Alive")) + 
  geom_line(aes(y = E7, color="Control")) + 
  geom_line(aes(y = E9, color="Alive")) +
  geom_line(aes(y = E11, color="Control")) + 
  geom_line(aes(y = G3, color="Alive")) + 
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Control")) + 
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) + 
  labs(title="EY107 Alive Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY107 ALum.png")

```

```{r Lum}
colors <- c("Alive" = "green", "Control" = "black", "Dead" = "red")

p <- ggplot(j, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Control")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Control")) + 
  geom_line(aes(y = C1, color="Alive")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  geom_line(aes(y = C5, color="Dead")) + 
  geom_line(aes(y = C7, color="Control")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) + 
  geom_line(aes(y = E3, color="Alive")) +
  geom_line(aes(y = E5, color="Alive")) + 
  geom_line(aes(y = E7, color="Control")) + 
  geom_line(aes(y = E9, color="Alive")) +
  geom_line(aes(y = E11, color="Control")) + 
  geom_line(aes(y = G3, color="Alive")) + 
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Control")) + 
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) + 
  labs(title="EY107 Fluor",
        x ="Time (min)", y = "Fluorescence(AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY107 Fluor.png")

```