---
title: "EY109 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(DescTools)

df <- read_excel("~/Documents/Experiments/4.30.26 EY109 Lum.xlsx", 
    sheet = "Sheet1")

df1 <- read_excel("~/Documents/Experiments/4.30.26 EY109 Lum.xlsx", 
    sheet = "Sheet3")
```

```{r}
#separate luminescence and fluorescence 
newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 


min <-c(0,12,24,36,48,60,72,84,96,108,120,132,144,156,168,180,192,204,216,228,240,252,264,276,288,300,312,324,336,348,360,372,384,396,408,420,432,444,456,468,480,492,504,516,528,540,552,564,576,588,600,612,624,636,648,660,672,684,696,708,720,732,744,756,768,780,792,804,816,828,840,852,864,876,888,900,912,924,936,948,960,972,984,996,1008,1020,1032,1044,1056,1068,1080,1092,1104,1116,1128) 

i <- cbind(newdf,min)
```

```{r Lum}
colors <- c("Alive" = "steelblue", "Control" = "black", "Dead" = "red")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Alive")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Alive")) + 
  geom_line(aes(y = C1, color="Alive")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  geom_line(aes(y = C5, color="Alive")) + 
  geom_line(aes(y = C7, color="Alive")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) +
  geom_line(aes(y = E1, color="Alive")) + 
  geom_line(aes(y = E3, color="Alive")) +
  geom_line(aes(y = E5, color="Alive")) + 
  geom_line(aes(y = E7, color="Alive")) + 
  geom_line(aes(y = E9, color="Alive")) +
  geom_line(aes(y = E11, color="Control")) +
  geom_line(aes(y = G1, color="Alive")) + 
  geom_line(aes(y = G3, color="Alive")) + 
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Alive")) + 
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) + 
  labs(title="EY109 Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY109 Lum.png")

```


```{r}
my_comparisons <- list( c("OD1", "OD5", "OD5F","OD0.5","OD2"))

p <- ggplot(df1, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY106 Lum AUC",
        x ="Condition", y = "Area Under Curve")
p



```

```{r}

newdata <- subset(i, min <= 1020)
newdata<- as.numeric()

my_vec <- numeric()

for (col in newdata) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)
```

```{r AUC}
df <- data.frame(dose=c("EY109","EY109","EY109","EY109","EY109","EY109","EY109","EY109","EY109","EY109","EY109","Control","EY109","EY109","EY109","EY109","EY109","Control","EY109","EY109","EY109","EY109","EY109","Control"),
    len=c(262884, 217188, 196686, 655002, 156306, 188868, 205632, 372594, 304302, 196722, 146040,  14058, 219972, 421446,304494, 187560, 461964,  14070, 270294, 160536, 202590, 201174, 551688,  13836))

    
my_comparisons <- list( c("EY109", "Control"))

p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY109 Lum AUC",
        x ="Condition", y = "Area Under Curve")
p


#ggsave("EY109 LAUC.png")
```