---
title: "EY110 Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(DescTools)

df <- read_excel("~/Documents/Experiments/5.8.26 EY110 Lum.xlsx", 
    sheet = "Sheet1")

```

```{r}
#separate luminescence and fluorescence 
newdf<- df %>%
  group_by(ID) %>%
  summarize(across(A1:G11, max)) 


min <-c(0,12,24,36,48,60,72,84,96,108,120,132,144,156,168,180,192,204,216,228,240,252,264,276,288,300,312,324,336,348,360,372,384,396,408,420,432,444,456,468,480,492,504,516,528,540,552,564,576,588,600,612,624,636,648,660,672,684,696,708,720,732,744,756,768,780,792,804,816,828,840,852,864,876,888,900,912,924,936,948,960,972,984,996,1008,1020) 

i <- cbind(newdf,min)
```

```{r Lum}
colors <- c("Alive" = "steelblue", "Control" = "black", "Dead" = "red")

p <- ggplot(i, aes(x=min)) + 
  geom_line(aes(y = A1, color="Alive")) + 
  geom_line(aes(y = A3, color="Alive")) + 
  geom_line(aes(y = A5, color="Alive")) + 
  geom_line(aes(y = A7, color="Alive")) + 
  geom_line(aes(y = A9, color="Alive")) + 
  geom_line(aes(y = A11, color="Control")) + 
  geom_line(aes(y = C1, color="Alive")) + 
  geom_line(aes(y = C3, color="Alive")) + 
  geom_line(aes(y = C5, color="Alive")) + 
  geom_line(aes(y = C7, color="Alive")) + 
  geom_line(aes(y = C9, color="Alive")) + 
  geom_line(aes(y = C11, color="Control")) + 
  geom_line(aes(y = E1, color="Alive")) + 
  geom_line(aes(y = E3, color="Alive")) +
  geom_line(aes(y = E5, color="Dead")) + 
  geom_line(aes(y = E7, color="Alive")) + 
  geom_line(aes(y = E9, color="Alive")) +
  geom_line(aes(y = E11, color="Control")) + 
  geom_line(aes(y = G1, color="Alive")) + 
  geom_line(aes(y = G3, color="Alive")) + 
  geom_line(aes(y = G5, color="Alive")) + 
  geom_line(aes(y = G7, color="Alive")) + 
  geom_line(aes(y = G9, color="Alive")) + 
  geom_line(aes(y = G11, color="Control")) + 
  labs(title="EY110 Lum",
        x ="Time (min)", y = "Luminescence (AU)", color = "Legend")+
    scale_color_manual(values = colors)
p
#ggsave("EY110 Lum.png")

```


```{r}

my_vec <- numeric()

for (col in i) {
    a <- AUC(min, col, method = c("trapezoid"))
    my_vec <- c(my_vec, a)
}

print(my_vec)
```

```{r AUC}
df <- data.frame(dose=c("EY110","EY110","EY110","EY110","EY110","Control","EY110","EY110","EY110","EY110","EY110","Control","EY110","EY110","Dead","EY110","EY110","Control","EY110","EY110","EY110","EY110","EY110","Control"),
    len=c(297672, 337992, 609390, 582924, 416418,  14178, 473838, 295158, 323616, 314832, 417858,  13902, 260712,525534, 888378, 312180, 620142,  14670, 233346, 316368, 321282, 416838, 439800,  13704))

    
my_comparisons <- list( c("EY110", "Control","Dead"))

p <- ggplot(df, aes(x=dose, y=len)) +
geom_bar(stat="summary", 
           fun=mean,
           aes(fill=dose)) +
  geom_point(position = position_jitter(width = 0.2), color = "black")+
  stat_compare_means(comparisons = my_comparisons)+
  labs(title="EY110 Lum AUC",
        x ="Condition", y = "Area Under Curve")
p


#ggsave("EY110 LAUC.png")
```